import{useRef,useState,useEffect}from'react';import{Download,Share2,Eye,EyeOff}from'lucide-react';import type{ConfirmedRecovery}from'./withdrawal';import{short}from'./api';
export default function RecoveryTicket({recovery}:{recovery:ConfirmedRecovery}){
 const ref=useRef<HTMLCanvasElement>(null);const[show,setShow]=useState(false);const[message,setMessage]=useState('');
 useEffect(()=>{setShow(false);},[recovery.recoveryId]);
 function draw(){const canvas=ref.current;if(!canvas)return;const c=canvas.getContext('2d');if(!c)return;c.fillStyle='#ffffff';c.fillRect(0,0,1080,1080);c.strokeStyle='#dbe3d8';c.lineWidth=2;c.strokeRect(34,34,1012,1012);c.fillStyle='#033419';c.fillRect(0,0,1080,15);c.font='bold 62px Arial';c.fillText('mova.',85,135);c.font='18px Arial';c.fillStyle='#61705f';c.fillText('NON-CUSTODIAL RECOVERY RECEIPT',85,180);c.fillStyle='#033419';c.font='bold 30px Arial';c.fillText('RECOVERY COMPLETE  ✓',85,285);c.font='bold 76px Arial';c.fillText(show?recovery.amount+' ETH':'Amount hidden',85,395);c.strokeStyle='#e1e6dc';c.beginPath();c.moveTo(85,460);c.lineTo(995,460);c.stroke();const fields=[['FROM',recovery.protocol],['NETWORK','Ethereum Mainnet'],['TO',short(recovery.destination)],['TRANSACTION',short(recovery.transactionHash)],['CONFIRMED',new Date(recovery.confirmedAt).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})]];fields.forEach(([label,value],i)=>{const y=522+i*76;c.fillStyle='#6d7869';c.font='15px Arial';c.fillText(label,85,y);c.fillStyle='#243c2b';c.font='26px Arial';c.fillText(value,85,y+34);});c.font='19px Arial';c.fillStyle='#033419';c.fillText(recovery.recoveryId,85,971);c.font='15px Arial';c.fillStyle='#75816e';c.fillText('A receipt, not a recovery key or authorization.',85,1007);}
 useEffect(draw,[show,recovery]);
 async function blob(){draw();const canvas=ref.current;if(!canvas)throw Error('Ticket is unavailable.');return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Ticket could not be generated.')),'image/png'));}
 async function download(){try{const b=await blob();const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download=`mova-recovery-${recovery.recoveryId}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);setMessage('Ticket downloaded.');}catch(e){setMessage(e instanceof Error?e.message:'Download failed.');}}
 async function share(){try{const b=await blob();const file=new File([b],`mova-recovery-${recovery.recoveryId}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'Mova recovery receipt'});setMessage('Sharing opened.');}else{await navigator.clipboard.writeText(`https://etherscan.io/tx/${recovery.transactionHash}`);setMessage('Transaction link copied. Download the image to share the ticket.');}}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setMessage('Sharing isn’t available here. Use Download to save the ticket.');}}
 return <section className="ticket-section"><h3>Your recovery ticket</h3><button className="text-button" aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>} {show?'Hide amount':'Show amount'}</button><canvas ref={ref} width={1080} height={1080} aria-label={`Recovery receipt for ${recovery.protocol}. ${show?recovery.amount+' ETH':'Amount hidden'}. ${recovery.recoveryId}.`} role="img"/><p className="fine-print">Hiding the amount changes this image only. The transaction and its amount remain public on-chain. This receipt grants no access to funds.</p><div className="ticket-actions"><button className="button dark" onClick={download}><Download size={16}/>Download PNG</button><button className="button ticket-share" onClick={share}><Share2 size={16}/>Share</button></div><p role="status" className="fine-print">{message}</p></section>;
}
