import{useEffect,useRef,useState}from'react';
import{ArrowLeft,ArrowUpRight,Check,Clock,Download,Info,LoaderCircle,LockKeyhole,RefreshCw,ShieldCheck}from'lucide-react';
import{formatEther,zeroAddress}from'viem';
import{displayAmount,short,networkFor,explorerFor,sunsetCheck,type Position,type StaderCheck,type SiliconProof}from'./api';
const staderGuide='https://stader.gitbook.io/stader/polygon-discontinued';
const siliconGuide='https://docs.silicon.network/user-guide/bridge/withdrawal';
export default function SunsetDetails({position,onBack,onRefresh,onDownload}:{position:Position;onBack:()=>void;onRefresh:()=>void;onDownload:()=>void}){
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[requestResult,setRequestResult]=useState<StaderCheck|null>(null),[claims,setClaims]=useState<Record<string,StaderCheck>>({}),[proofs,setProofs]=useState<Record<number,SiliconProof>>({});
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{setBusy('');setError('');setRequestResult(null);setClaims({});setProofs({});return()=>controller.current?.abort();},[position]);
 async function checkStader(kind:'request'|'claim',key?:string){if(busy)return;const ctrl=new AbortController();controller.current=ctrl;setBusy(key||'request');setError('');if(key)setClaims(old=>{const next={...old};delete next[key];return next;});else setRequestResult(null);try{const result=await sunsetCheck<StaderCheck>('stader-check',{wallet:position.wallet,kind,...(key?{requestKey:key}:{})},ctrl.signal);if(result.simulation!=='passed'||result.signingEnabled!==false||result.stage!==(kind==='claim'?'claim_only':'request_only')||(kind==='claim'&&result.requestKey!==key)||(kind==='request'&&(!/^[1-9][0-9]*$/.test(result.amountWei||'')||BigInt(result.amountWei!)>1000000000000000n||BigInt(result.amountWei!)>BigInt(position.amountWei))))throw Error('The check returned an unexpected result. Refresh this position.');if(!ctrl.signal.aborted){if(key)setClaims(old=>({...old,[key]:result}));else setRequestResult(result);}}catch(e){if(!ctrl.signal.aborted)setError(e instanceof Error?e.message:'The check failed.');}finally{if(!ctrl.signal.aborted)setBusy('');}}
 async function checkProof(count:number){if(busy)return;const ctrl=new AbortController();controller.current=ctrl;setBusy(String(count));setError('');setProofs(old=>{const next={...old};delete next[count];return next;});try{const result=await sunsetCheck<SiliconProof>('silicon-proof',{wallet:position.wallet,depositCount:count},ctrl.signal);const expected=position.silicon?.exits.find(e=>e.depositCount===count);if(!expected||result.depositCount!==count||result.signingEnabled!==false||result.sourceCodeVerified!==true||result.sourceEventVerified!==true||result.proofVerified!==true||result.amountWei!==expected.amountWei||result.sourceHash?.toLowerCase()!==expected.sourceHash.toLowerCase()||result.asset.toLowerCase()!==(expected.token===zeroAddress?'eth':expected.token.toLowerCase())||!['already_claimed','proof_checked','waiting_for_root'].includes(result.status)||(result.status==='already_claimed'&&!result.claimed)||(result.status==='proof_checked'&&(result.claimed||!result.rootRegistered))||(result.status==='waiting_for_root'&&(result.claimed||result.rootRegistered)))throw Error('The proof check returned an unexpected result.');if(!ctrl.signal.aborted)setProofs(old=>({...old,[count]:result}));}catch(e){if(!ctrl.signal.aborted)setError(e instanceof Error?e.message:'The proof check failed.');}finally{if(!ctrl.signal.aborted)setBusy('');}}
 function exportChecks(){try{const report={product:'Mova Recovery',type:'read_only_sunset_checks',recoveryCompleted:false,signingEnabled:false,position,requestSimulation:requestResult,claimSimulations:claims,exitProofChecks:proofs};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mova-${position.protocol.id}-check-${position.blockNumber}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}catch{onDownload();}}
 const stader=position.stader,silicon=position.silicon;
 return <div className="sunset-details">
  <button className="back-button" onClick={onBack}><ArrowLeft size={14}/>Back to project checks</button>
  <div className="result-label"><span className="green-dot"/>{position.protocol.name} · {networkFor(position.protocol)}</div>
  <h2>{stader?'Your MaticX and withdrawals':'Your Silicon exit check'}</h2>
  <p className="card-description">{stader?'MaticX holdings and existing withdrawal requests are checked separately. A request is not a completed recovery.':'Native ETH and returned bridge-exit records for this address. Other token balances may still exist and are not checked here.'}</p>
  <div className="sunset-owner"><span>Address checked</span><strong>{position.wallet}</strong></div>
  {stader&&<>
   <div className="sunset-balance"><span>MaticX held</span><strong>{displayAmount(position.amount)} <small>MaticX</small></strong>{stader.quoteWei!==null&&<p>Current conversion quote: {displayAmount(formatEther(BigInt(stader.quoteWei)))} POL. Not a guaranteed payout.</p>}</div>
   <ol className="sunset-stages" aria-label="Stader withdrawal stages"><li><span>1</span><div><strong>Request</strong><p>MaticX is burned and a withdrawal request is created.</p></div></li><li><span>2</span><div><strong>Wait for checkpoints</strong><p>Current delay: {stader.delayEpochs} epochs. This is not a fixed number of days.</p></div></li><li><span>3</span><div><strong>Claim POL</strong><p>An eligible claim pays POL tokens on Ethereum. Gas is paid in ETH.</p></div></li></ol>
   <div className="sunset-note"><Info size={18}/><p>{stader.instant?'The contract currently reports instant-redemption mode. The queued request path is not offered in that mode.':stader.paused?'New requests are currently paused. Existing claims are evaluated separately.':'The contract currently reports the queued request-and-claim mode.'} Mova signing is not enabled for Stader; these controls only simulate.</p></div>
   {BigInt(position.amountWei)>0n&&!stader.instant&&!stader.paused&&!stader.custodied&&<><button className="button dark wide" disabled={!!busy} onClick={()=>checkStader('request')}>{busy==='request'?<LoaderCircle className="spin" size={16}/>:<ShieldCheck size={16}/>}Check a small request</button><p className="fine-print">Simulates at most 0.001 MaticX. No wallet approval or transaction is requested.</p></>}
   {requestResult&&<div className="simulation-panel passed" role="status"><Check size={18}/><div><strong>Request simulation passed</strong><p>{requestResult.amountWei?formatEther(BigInt(requestResult.amountWei)):''} MaticX · block {requestResult.blockNumber}. {requestResult.note}</p>{requestResult.gasEstimate&&<p>Estimated gas units: {requestResult.gasEstimate}. ETH/USD fee quote unavailable.</p>}</div></div>}
   <h3 className="sunset-section-title">Withdrawal requests <span>{stader.requests.length}</span></h3>
   <p className="fine-print">Current checkpoint epoch: {stader.currentEpoch}. Request indexes may change after a claim; Mova checks the request identity again.</p>
   {!stader.requests.length?<p className="sunset-empty">No outstanding requests were returned at this block.</p>:<div className="sunset-request-list">{stader.requests.map(r=><article key={r.key} className="sunset-request"><div className="sunset-request-head"><strong>Request {r.index+1}</strong><span>{r.state==='waiting'?<Clock size={14}/>:<ShieldCheck size={14}/>} {r.state==='waiting'?'Waiting':'Eligible to check'}</span></div><dl className="review-details"><div><dt>Eligible from epoch</dt><dd>{r.eligibleEpoch}</dd></div><div><dt>Validator</dt><dd>{short(r.validatorAddress)}</dd></div><div><dt>Validator request nonce</dt><dd>{r.validatorNonce}</dd></div><div><dt>Output</dt><dd>POL on Ethereum<small>Exact claim amount is not quoted by this check</small></dd></div></dl>{r.state==='epoch_eligible'&&<button className="button dark wide" disabled={!!busy} onClick={()=>checkStader('claim',r.key)}>{busy===r.key?<LoaderCircle className="spin" size={15}/>:<ShieldCheck size={15}/>}Check this claim</button>}{claims[r.key]&&<div className="simulation-panel passed" role="status"><Check size={16}/><div><strong>Claim simulation passed</strong><p>{claims[r.key].note}</p></div></div>}</article>)}</div>}
   <a className="button sunset-guide wide" href={staderGuide} target="_blank" rel="noreferrer">Read Stader’s official withdrawal guide<ArrowUpRight size={16}/></a>
   <p className="fine-print">The official guide covers Ethereum and Polygon separately. This Mova check covers Ethereum only. Do not use a Polygon token address for this position.</p>
  </>}
  {silicon&&<>
   <div className="sunset-deadline"><Clock size={19}/><div><strong>Withdrawal support deadline</strong><p>31 December 2026 · 04:00 Lagos time</p><small>03:00 UTC. The operator warns of network termination. Do not wait until the deadline.</small></div></div>
   <div className="sunset-balance"><span>Native ETH on Silicon</span><strong>{displayAmount(position.amount)} <small>ETH</small></strong><p>This includes ETH needed for gas; it is not an amount Mova has verified as withdrawable.</p></div>
   <div className="sunset-note"><LockKeyhole size={18}/><p>Mova can check exit evidence, but cannot submit Silicon withdrawals yet. Bridge source matching and a local native-ETH exit test passed, but production signing and recovery tracking are not ready. A checked proof is not a completed recovery.</p></div>
   <ol className="sunset-stages" aria-label="Silicon exit stages"><li><span>1</span><div><strong>Withdraw on Silicon</strong><p>Starting an exit alone does not return funds to Ethereum.</p></div></li><li><span>2</span><div><strong>Wait for proof readiness</strong><p>The exit must be included in a root accepted on Ethereum.</p></div></li><li><span>3</span><div><strong>Finalize on Ethereum</strong><p>Use the official bridge’s finalization step. Check the resulting asset receipt.</p></div></li></ol>
   {silicon.historyError&&<div className="error-panel" role="alert"><Info size={17}/><p>{silicon.historyError}</p></div>}
   <h3 className="sunset-section-title">Returned exit records <span>{silicon.exits.length}</span></h3>
   <p className="fine-print">{silicon.coverage} {silicon.historyLimited?'More history exists than is shown here. Use the official bridge for the complete list.':''}</p>
   {!silicon.historyError&&!silicon.exits.length&&<p className="sunset-empty">No matching Ethereum-bound exits were returned. This does not rule out token balances or other activity.</p>}
   <div className="sunset-request-list">{silicon.exits.map(e=><article key={e.globalIndex} className="sunset-request"><div className="sunset-request-head"><strong>Exit #{e.depositCount}</strong><span>{proofs[e.depositCount]?.claimed||e.state==='claimed'?'Already claimed':e.state==='unclaimed'?'Unclaimed on Ethereum':e.state==='check_failed'?'Status check failed':'Status not yet checked'}</span></div><dl className="review-details"><div><dt>Asset</dt><dd>{e.token===zeroAddress?'Native ETH':`Token ${short(e.token)}`}</dd></div><div><dt>Amount</dt><dd>{e.token===zeroAddress?`${displayAmount(formatEther(BigInt(e.amountWei)))} ETH`:`${e.amountWei} base units`}</dd></div><div><dt>Destination</dt><dd>{short(e.destination)}<small>Ethereum Mainnet</small></dd></div></dl><a className="text-button" href={`https://scope.silicon.network/tx/${e.sourceHash}`} target="_blank" rel="noreferrer">View Silicon transaction<ArrowUpRight size={14}/></a>{e.verificationEnabled&&<button className="button dark wide" disabled={!!busy} onClick={()=>checkProof(e.depositCount)}>{busy===String(e.depositCount)?<LoaderCircle className="spin" size={15}/>:<ShieldCheck size={15}/>}Check exit proof</button>}{!e.verificationEnabled&&<p className="fine-print">This token origin is not supported by Mova’s exit proof checker.</p>}{proofs[e.depositCount]&&<div className="sunset-proof-result" role="status"><strong>{proofs[e.depositCount].status==='already_claimed'?'Already claimed — do not submit again':proofs[e.depositCount].status==='proof_checked'?'Exit proof checked — not a recovery':'Waiting for Ethereum root registration'}</strong><p>{proofs[e.depositCount].message}</p><small>Ethereum block {proofs[e.depositCount].ethereumBlock}</small></div>}</article>)}</div>
   <a className="button sunset-guide wide" href="https://bridge.silicon.network/login" target="_blank" rel="noreferrer">Open the official Silicon bridge<ArrowUpRight size={16}/></a><a className="text-button center" href={siliconGuide} target="_blank" rel="noreferrer">Read the official exit instructions<ArrowUpRight size={14}/></a>
   <p className="fine-print">Do not make new deposits into Silicon. Tokens issued only on Silicon may not have a direct Ethereum exit. Never share a seed phrase or private key.</p>
  </>}
  {error&&<div className="error-panel" role="alert"><Info size={17}/><p>{error}</p></div>}
  <div className="sunset-block"><span>Read on {networkFor(position.protocol)}</span><a href={`${explorerFor(position.protocol)}/block/${position.blockNumber}`} target="_blank" rel="noreferrer">Block {position.blockNumber}<ArrowUpRight size={13}/></a></div>
  <button className="button dark wide" disabled={!!busy} onClick={onRefresh}><RefreshCw size={16}/>Refresh project checks</button>
  <button className="text-button center" onClick={exportChecks}><Download size={14}/>Download this check report</button>
  <p className="fine-print">Checking does not establish wallet control. No transaction is submitted and no recovery ticket is issued by these checks.</p>
 </div>;
}
