import{useState,useEffect,useRef,useCallback}from'react';
import{ArrowRight,Check,ExternalLink,Info,LoaderCircle,LockKeyhole,RefreshCw,Wallet}from'lucide-react';
import{formatEther}from'viem';
import Modal from'./Modal';import RecoveryTicket from'./RecoveryTicket';import type{Provider}from'./wallet';import type{Position}from'./api';import{short}from'./api';
import{withdrawalName,withdrawalRequest,loadTracking,saveTracking,TRACKING_KEY,type PreparedWithdrawal,type TrackingRecord,type MonitoredWithdrawal}from'./withdrawal';
export default function WithdrawalFlow({position,provider,connected,onClose,onConnect}:{position:Position|null;provider:Provider|null;connected:string;onClose:()=>void;onConnect:()=>void}){
 const[open,setOpen]=useState(false),[prepared,setPrepared]=useState<PreparedWithdrawal|null>(null),[eligibility,setEligibility]=useState<{enabled:boolean;maxWithdrawalWei:string;confirmations:number}|null>(null),[record,setRecord]=useState<TrackingRecord|null>(null),[status,setStatus]=useState<MonitoredWithdrawal|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[consent,setConsent]=useState(false),[now,setNow]=useState(Date.now()),[tick,setTick]=useState(0),[hashInput,setHashInput]=useState(''),[ticket,setTicket]=useState(false),[storageProblem,setStorageProblem]=useState(false);
 const generation=useRef(0);const active=useRef(true);const signing=useRef(false);
 const close=useCallback(()=>{generation.current++;setPrepared(null);setConsent(false);setOpen(false);onClose();},[onClose]);
 useEffect(()=>{active.current=true;try{const saved=loadTracking();if(saved){setRecord(saved);setOpen(true);}}catch(e){setStorageProblem(true);setError(e instanceof Error?e.message:'Saved tracking could not be loaded.');setOpen(true);}const sync=()=>{try{setRecord(loadTracking());setPrepared(null);setConsent(false);}catch{setStorageProblem(true);}};window.addEventListener('storage',sync);return()=>{active.current=false;generation.current++;window.removeEventListener('storage',sync);};},[]);
 useEffect(()=>{if(!position)return;setOpen(true);setPrepared(null);setEligibility(null);setConsent(false);setError('');setNotice('');setTicket(false);const id=++generation.current;withdrawalRequest<{enabled:boolean;maxWithdrawalWei:string;confirmations:number}>('pilot-status',{wallet:position.wallet,projectId:position.protocol.id}).then(v=>{if(id===generation.current)setEligibility(v);}).catch(e=>{if(id===generation.current)setError(e.message);});},[position]);
 useEffect(()=>{const invalidate=()=>{generation.current++;setPrepared(null);setConsent(false);if(!signing.current)setError('Wallet identity or network changed. Verify the withdrawal again before signing.');};provider?.on?.('accountsChanged',invalidate);provider?.on?.('chainChanged',invalidate);provider?.on?.('disconnect',invalidate);return()=>{provider?.removeListener?.('accountsChanged',invalidate);provider?.removeListener?.('chainChanged',invalidate);provider?.removeListener?.('disconnect',invalidate);};},[provider]);
 useEffect(()=>{if(!prepared)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[prepared]);
 useEffect(()=>{if(!record||!open)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const result=await withdrawalRequest<MonitoredWithdrawal>('withdrawal-status',{envelope:record!.envelope,...(record!.hash?{hash:record!.hash}:{})});if(!cancelled){setStatus(result);setError('');}}catch(e){if(!cancelled){setStatus(null);setError(e instanceof Error?e.message:'Monitoring is temporarily unavailable. The transaction may still confirm.');}}if(!cancelled)timer=setTimeout(poll,12000);}poll();return()=>{cancelled=true;clearTimeout(timer);};},[record?.envelope,record?.hash,open,tick]);
 async function prepare(){if(!position||record||busy||storageProblem)return;setBusy('preparing');setPrepared(null);setConsent(false);setError('');setNotice('');const id=++generation.current;try{if(loadTracking())throw Error('A withdrawal is already being tracked. Resume it before starting a new one.');const result=await withdrawalRequest<PreparedWithdrawal>('prepare-withdrawal',{wallet:position.wallet,projectId:position.protocol.id});if(result.signingEnabled!==true||result.verification?.simulation!=='passed'||result.plan.wallet.toLowerCase()!==position.wallet.toLowerCase()||(result.plan.projectId||'etherdelta-eth')!==position.protocol.id||result.plan.tx.to.toLowerCase()!==position.protocol.contract.toLowerCase())throw Error('The prepared request did not match the selected position. Nothing was submitted.');if(id===generation.current){setPrepared(result);setNow(Date.now());}}catch(e){if(id===generation.current)setError(e instanceof Error?e.message:'Preparation failed.');}finally{if(active.current)setBusy('');}}
 async function sign(){
  if(!prepared||!provider||busy||record||!consent||Date.now()>prepared.plan.expiresAt||storageProblem)return;
  if(!navigator.locks){setError('This browser does not support the cross-tab protection required for the controlled test. Use an up-to-date supported browser.');return;}
  const ready=prepared;const id=generation.current;setBusy('verifying');setError('');
  await navigator.locks.request('mova-recovery-submission',{ifAvailable:true},async lock=>{
   if(!lock){setError('Another tab is handling this wallet request. Do not submit again.');return;}
   let saved:TrackingRecord|null=null;
   try{
    if(loadTracking())throw Error('A recovery is already being tracked. Do not submit another request.');
    const assertWallet=async()=>{try{const[accounts,chain]=await Promise.all([provider.request({method:'eth_accounts'}),provider.request({method:'eth_chainId'})]);if(!Array.isArray(accounts)||accounts[0]?.toLowerCase()!==ready.plan.wallet.toLowerCase()||Number(chain)!==1)throw Error();}catch{throw Error('The wallet account or network could not be matched to the reviewed recovery.');}};
    await assertWallet();const verified=await withdrawalRequest<{simulation:string}>('verify-withdrawal',{envelope:ready.envelope});if(verified.simulation!=='passed')throw Error('The exact request did not pass fresh verification. Nothing was submitted.');await assertWallet();
    if(id!==generation.current||!active.current||Date.now()>ready.plan.expiresAt)throw Error('Wallet state or verification changed. Review a new request.');
    saved={version:1,envelope:ready.envelope,plan:ready.plan,savedAt:Date.now()};saveTracking(saved);setRecord(saved);setStatus(null);signing.current=true;setBusy('signing');
    // The exact frozen fields reviewed and simulated are passed to the external wallet.
    const hash=await provider.request({method:'eth_sendTransaction',params:[{...ready.plan.tx}]});
    if(typeof hash!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(hash))throw Error('The wallet returned no valid transaction hash. Check your wallet; do not submit another request.');
    const submitted={...saved,hash};try{saveTracking(submitted);}catch{setNotice('The hash could not be saved locally. Copy it from your wallet before closing this page.');}setRecord(submitted);setStatus({status:'pending',hash,message:'The wallet returned a transaction hash. Waiting for on-chain verification.'});setPrepared(null);
   }catch(e:any){
    if(saved&&e?.code===4001){try{localStorage.removeItem(TRACKING_KEY);}catch{}setRecord(null);setStatus(null);setPrepared(null);setNotice('Recovery cancelled. The wallet reported that you rejected the transaction; no withdrawal was approved.');}
    else{if(saved){setRecord(saved);setStatus({status:'submission_unknown',message:'The wallet request did not complete normally. Check your wallet before doing anything else; Mova will not resubmit it.'});setPrepared(null);}setError(saved?'The wallet request could not be completed. Check your wallet; do not retry a possibly submitted transaction.':e instanceof Error?e.message:'The request could not be verified.');}
   }finally{signing.current=false;}
  }).catch(()=>setError('The browser could not acquire the submission lock. No new request was issued by this action.'));
  setBusy('');
 }
 function clearRecord(){if(busy)return;if(!window.confirm('This only removes local tracking; it does not cancel a transaction. Only continue after checking your wallet and confirming no unresolved withdrawal is pending.'))return;try{localStorage.removeItem(TRACKING_KEY);setRecord(null);setStatus(null);setPrepared(null);setConsent(false);setStorageProblem(false);setError('');setNotice('Local tracking removed. No transaction was submitted or cancelled.');}catch{setError('The saved record could not be removed.');}}
 function attachHash(){if(!record)return;if(!/^0x[0-9a-fA-F]{64}$/.test(hashInput)){setError('Enter the full transaction hash from your wallet.');return;}const updated={...record,hash:hashInput};try{saveTracking(updated);setRecord(updated);setStatus(null);setError('');setHashInput('');}catch{setError('The transaction hash could not be saved.');}}
 const ownerConnected=!!position&&!!provider&&connected.toLowerCase()===position.wallet.toLowerCase();
 const expired=!!prepared&&now>=prepared.plan.expiresAt;
 const recovery=status?.status==='confirmed'?status.recovery:undefined;
 const title=recovery?'Recovery complete':busy==='signing'?'Confirm in your wallet':record?'Track your withdrawal':'Review controlled withdrawal';
 return <>{!open&&(record||storageProblem)&&<button className="resume-recovery button dark" onClick={()=>setOpen(true)}><RefreshCw size={15}/>Resume recovery tracking</button>}{open&&<Modal title={title} onClose={close}>
  {!record&&!storageProblem&&<>
   <p className="modal-intro">{position?.protocol.name} · Ethereum Mainnet. This controlled flow withdraws at most 0.001 ETH to the position owner. {position?.protocol.id==='foundation-feth'?'Available FETH is redeemed 1:1 for ETH; locked funds are excluded. This proxy can be upgraded after simulation. The pilot requires execution tracing and a separate FETH review approval.':'Only the native ETH position is included.'}</p>
   {!ownerConnected?<div className="info-panel"><Wallet size={18}/><div><p>Connect the wallet that owns this position before reviewing a real withdrawal.</p><button className="text-button" onClick={()=>{close();onConnect();}}>Connect owner wallet<ArrowRight size={14}/></button></div></div>:!eligibility?<p role="status"><LoaderCircle className="spin" size={16}/> Checking pilot availability…</p>:!eligibility.enabled?<div className="info-panel"><LockKeyhole size={18}/><p>This wallet is not enabled for the controlled recovery test. Discovery and read-only simulation remain available. The operator must complete the review gate and explicitly approve the tester’s public address.</p></div>:<>
    {!prepared?<button className="button primary wide" disabled={!!busy} onClick={prepare}>{busy==='preparing'?<><LoaderCircle className="spin" size={16}/>Preparing and simulating…</>:<>Prepare exact withdrawal<ArrowRight size={16}/></>}</button>:<>
     <dl className="review-details pilot-summary"><div><dt>{prepared.plan.projectId==='foundation-feth'?'Receive':'Withdraw'}</dt><dd>{formatEther(BigInt(prepared.plan.amountWei))} ETH</dd></div><div><dt>From</dt><dd>{withdrawalName(prepared.plan)}<small className="address-wrap">{prepared.plan.tx.to}</small></dd></div><div><dt>Destination</dt><dd>Your connected wallet<small className="address-wrap">{prepared.plan.wallet}</small></dd></div><div><dt>Network</dt><dd>Ethereum Mainnet</dd></div><div><dt>Estimated fee</dt><dd>{formatEther(BigInt(prepared.estimatedFeeWei))} ETH</dd></div><div><dt>Maximum fee at these settings</dt><dd>{formatEther(BigInt(prepared.maxFeeWei))} ETH</dd></div></dl>
     <div className={`simulation-panel ${expired?'':'passed'}`}><Check size={19}/><div><strong>{expired?'Verification expired':'Exact request simulated successfully'}</strong><p>{expired?'Prepare a new request before signing.':`Expires in ${Math.max(0,Math.ceil((prepared.plan.expiresAt-now)/1000))} seconds. The same request is checked again immediately before wallet approval.`}</p></div></div>
     {BigInt(prepared.maxFeeWei)>=BigInt(prepared.plan.amountWei)&&<div className="error-panel"><Info size={17}/><p>The maximum network fee is as large as or larger than this withdrawal. You may prefer not to proceed.</p></div>}
     {prepared.plan.projectId==='foundation-feth'&&<p className="fine-print">This burns {formatEther(BigInt(prepared.plan.amountWei))} available FETH and pays the same amount of ETH to your wallet. No token approval is requested. Locked FETH is untouched.</p>}
     <label className="pilot-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I reviewed the amount, destination and fees. A failed transaction can still cost gas. Public transaction details will be stored in this browser for tracking.</span></label>
     <button className="button primary wide" disabled={!!busy||expired||!consent} onClick={sign}>{busy?<><LoaderCircle className="spin" size={16}/>Re-verifying request…</>:<>Recover funds<ArrowRight size={16}/></>}</button><button className="text-button center" disabled={!!busy} onClick={prepare}>Prepare a fresh request</button>
     <p className="fine-print">Do not change the amount, recipient, data, gas or fee fields in your wallet. If the wallet changes the transaction, Mova will flag the mismatch instead of issuing a recovery ticket. USD estimates are unavailable.</p>
    </>}
   </>}
  </>}
  {record&&<>
   <p className="modal-intro">{busy==='signing'?'Your wallet will ask you to approve this withdrawal. Do not open another recovery request.':recovery?'The supported withdrawal and its on-chain result were verified.':'This record is saved locally. Refreshing resumes checks; it never resubmits the transaction.'}</p>
   <dl className="review-details pilot-summary"><div><dt>Amount</dt><dd>{formatEther(BigInt(record.plan.amountWei))} ETH</dd></div><div><dt>From</dt><dd>{withdrawalName(record.plan)}</dd></div><div><dt>To</dt><dd className="address-wrap">{record.plan.wallet}</dd></div><div><dt>Network</dt><dd>Ethereum Mainnet</dd></div><div><dt>Maximum fee in request</dt><dd>{formatEther(BigInt(record.plan.tx.gas)*BigInt(record.plan.tx.gasPrice))} ETH</dd></div>{record.hash&&<div><dt>Transaction ID</dt><dd className="address-wrap">{record.hash}</dd></div>}</dl>
   {!recovery&&<div className="info-panel" role="status">{busy==='signing'||!status||status.status==='pending'||status.status==='confirming'?<LoaderCircle className="spin" size={18}/>:<Info size={18}/>}<p>{busy==='signing'?'Waiting for wallet confirmation…':status?.message||'Verifying this record against Ethereum…'}{status?.status==='confirming'&&` ${status.confirmations} of ${status.requiredConfirmations} confirmations.`}</p></div>}
   {recovery&&<div className="simulation-panel passed"><Check size={19}/><div><strong>Recovery complete</strong><p>{recovery.amount} ETH withdrawn to the position owner. {status?.confirmations} confirmations verified.</p></div></div>}
   {record.hash&&<a className="button dark wide" href={`https://etherscan.io/tx/${record.hash}`} target="_blank" rel="noreferrer">View transaction<ExternalLink size={15}/></a>}
   {!recovery&&<button className="text-button center" disabled={!!busy} onClick={()=>setTick(t=>t+1)}><RefreshCw size={14}/>Check status again</button>}
   {!busy&&(!record.hash||status?.status==='replaced_or_nonce_used'||status?.status==='confirmation_timeout')&&<div className="attach-hash"><label htmlFor="recovery-tx-hash">Have a transaction hash from your wallet?</label><input id="recovery-tx-hash" value={hashInput} onChange={e=>setHashInput(e.target.value)} placeholder="0x…" spellCheck={false}/><button className="text-button" onClick={attachHash}>Track this hash</button><p className="fine-print">The transaction must match the original request. A changed replacement is flagged, not silently accepted.</p></div>}
   {recovery&&<><button className="text-button center" onClick={()=>setTicket(!ticket)}>{ticket?'Hide recovery ticket':'Get recovery ticket'}</button>{ticket&&<RecoveryTicket recovery={recovery}/>}</>}
  </>}
  {notice&&<p className="fine-print" role="status">{notice}</p>}{error&&<div className="error-panel" role="alert"><Info size={17}/><p>{error}</p></div>}
  {(record||storageProblem)&&!busy&&<button className="text-button center" onClick={clearRecord}>{recovery?'Finish and remove local tracking':status?.status==='reverted'?'Remove failed record and review again':'Remove local tracking only'}</button>}
 </Modal>}</>;
}
